export const productsAPI = "http://localhost:5000/items";

export const mockProducts = {
  products: [
    {
      id: "image1",
      imageUrl: "image1.jpg",
      colorHex: "maroon",
      colorDisplay: "maroon",
      title: "Cat Tee Black T-Shirt",
      description: "4 MSL",
      availableSize: "XS",
      price: 10,
      currencyFormat: "₹",
    },
    {
      id: "image2",
      imageUrl: "image2.jpg",
      colorHex: "white",
      colorDisplay: "white",
      title: "Cat Tee Black T-Shirt",
      description: "4 MSL",
      availableSize: "XS",
      price: 11,
      currencyFormat: "₹",
    },
    {
      id: "image3",
      imageUrl: "image3.jpg",
      colorHex: "yellow",
      colorDisplay: "yellow",
      title: "Cat Tee Black T-Shirt",
      description: "4 MSL",
      availableSize: "XS",
      price: 12,
      currencyFormat: "₹",
    },
    {
      id: "image4",
      imageUrl: "image4.jpg",
      colorHex: "black",
      colorDisplay: "black",
      title: "Cat Tee Black T-Shirt",
      description: "4 MSL",
      availableSize: "XS",
      price: 13,
      currencyFormat: "₹",
    },
    {
      id: "image5",
      imageUrl: "image5.jpg",
      colorHex: "yellow",
      colorDisplay: "yellow",
      title: "Cat Tee Black T-Shirt",
      description: "4 MSL",
      availableSize: "XS",
      price: 14,
      currencyFormat: "₹",
    },
    {
      id: "image6",
      imageUrl: "image6.jpg",
      colorHex: "maroon",
      colorDisplay: "maroon",
      title: "Cat Tee Black T-Shirt",
      description: "4 MSL",
      availableSize: "XS",
      price: 15,
      currencyFormat: "₹",
    },
    {
      id: "image7",
      imageUrl: "image7.jpg",
      colorHex: "pink",
      colorDisplay: "pink",
      title: "Cat Tee Black T-Shirt",
      description: "4 MSL",
      availableSize: "XS",
      price: 16,
      currencyFormat: "₹",
    },
    {
      id: "image8",
      imageUrl: "image8.jpg",
      colorHex: "black",
      colorDisplay: "black",
      title: "Cat Tee Black T-Shirt",
      description: "4 MSL",
      availableSize: "XS",
      price: 17,
      currencyFormat: "₹",
    },
    {
      id: "image9",
      imageUrl: "image9.jpg",
      colorHex: "black",
      colorDisplay: "black",
      title: "Cat Tee Black T-Shirt",
      description: "4 MSL",
      availableSize: "XS",
      price: 18,
      currencyFormat: "₹",
    },
    {
      id: "image10",
      imageUrl: "image10.jpg",
      colorHex: "blue",
      colorDisplay: "blue",
      title: "Cat Tee Black T-Shirt",
      description: "4 MSL",
      availableSize: "XS",
      price: 19,
      currencyFormat: "₹",
    },
    {
      id: "image11",
      imageUrl: "image11.jpg",
      colorHex: "maroon",
      colorDisplay: "maroon",
      title: "Cat Tee Black T-Shirt",
      description: "4 MSL",
      availableSize: "XS",
      price: 20,
      currencyFormat: "₹",
    },
    {
      id: "image12",
      imageUrl: "image12.jpg",
      colorHex: "brown",
      colorDisplay: "brown",
      title: "Cat Tee Black T-Shirt",
      description: "4 MSL",
      availableSize: "XS",
      price: 21,
      currencyFormat: "₹",
    },
    {
      id: "image13",
      imageUrl: "image13.jpg",
      colorHex: "orange",
      colorDisplay: "orange",
      title: "Cat Tee Black T-Shirt",
      description: "4 MSL",
      availableSize: "XS",
      price: 22,
      currencyFormat: "₹",
    },
    {
      id: "image14",
      imageUrl: "image14.jpg",
      colorHex: "purple",
      colorDisplay: "purple",
      title: "Cat Tee Black T-Shirt",
      description: "4 MSL",
      availableSize: "XS",
      price: 23,
      currencyFormat: "₹",
    },
  ],
};
